FROM --platform=amd64 oven/bun:latest as runner

FROM --platform=amd64 node:18-slim as builder

WORKDIR /app

COPY . .
COPY --from=runner /usr/local/bin/bun /usr/local/bin
COPY --from=runner /usr/local/bin/bunx /usr/local/bin

RUN bun install && \
    bun run build

FROM runner    

WORKDIR /app

COPY --from=builder /app/build ./build

ENV PORT=8080 \
    RUNTIME_ENV=bun

EXPOSE 8080        

CMD ["bun", "run", "--bun", "./build/index.js"]